version: "3.8"

services:
  mongo:
    image: mongo:6.0
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: bookstore
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: bookstore-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/bookstore
    restart: always

volumes:
  mongo-data:
